name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - name: Download artifacts
#      uses: actions/download-artifact@v3
#      with:
#        name: build-artifact
#        path: /home/runner/work/autoclicker-rs/autoclicker-rs/target/debug
      
    - name: Install dependencies
      run: sudo apt install libx11-dev libxtst-dev libudev-dev libinput-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Uploading artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: /home/runner/work/autoclicker-rs/autoclicker-rs/target/debug
      
